version: "3"
services:
  sbconsole:
    image: jituhooda/keycloak-source:24

    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 5008:8080
    volumes:
      - ./keycloak-data:/app
    networks:
      - common-network

  #Docker Networks
networks:
  common-network:
    driver: bridge
